// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "wangxiao05@inspur.com",
            "url": "http://10.110.55.12:8888/wangxiao"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "测试Description",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "测试Summary",
                "responses": {}
            }
        },
        "/v1/sso/id_token": {
            "post": {
                "description": "生成id_token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "生成id_token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正确返回",
                        "schema": {
                            "$ref": "#/definitions/model.OKResponse"
                        }
                    },
                    "400": {
                        "description": "参数（token错误）错误返回",
                        "schema": {
                            "$ref": "#/definitions/model.TokenErrorResponse"
                        }
                    },
                    "500": {
                        "description": "服务器错误返回",
                        "schema": {
                            "$ref": "#/definitions/model.ServerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.IdToken": {
            "type": "object",
            "properties": {
                "id_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIxxxxxxx"
                }
            }
        },
        "model.OKResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "0000"
                },
                "data": {
                    "$ref": "#/definitions/model.IdToken"
                },
                "message": {
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "model.ServerErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "0011"
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "server internal error"
                }
            }
        },
        "model.TokenErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "0704"
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "token error"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "INSPUR-TENCENTMEETING-SSO",
	Description:      "浪潮集团腾讯会议sso免登录获取id_token服务.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
