definitions:
  model.IdToken:
    properties:
      id_token:
        example: eyJhbGciOiJSUzI1NiIxxxxxxx
        type: string
    type: object
  model.OKResponse:
    properties:
      code:
        example: "0000"
        type: string
      data:
        $ref: '#/definitions/model.IdToken'
      message:
        example: OK
        type: string
    type: object
  model.ServerErrorResponse:
    properties:
      code:
        example: "0011"
        type: string
      data: {}
      message:
        example: server internal error
        type: string
    type: object
  model.TokenErrorResponse:
    properties:
      code:
        example: "0704"
        type: string
      data: {}
      message:
        example: token error
        type: string
    type: object
info:
  contact:
    name: wangxiao05@inspur.com
    url: http://10.110.55.12:8888/wangxiao
  description: 浪潮集团腾讯会议sso免登录获取id_token服务.
  title: INSPUR-TENCENTMEETING-SSO
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: 测试Description
      produces:
      - application/json
      responses: {}
      summary: 测试Summary
  /v1/sso/id_token:
    post:
      consumes:
      - application/json
      description: 生成id_token
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 正确返回
          schema:
            $ref: '#/definitions/model.OKResponse'
        "400":
          description: 参数（token错误）错误返回
          schema:
            $ref: '#/definitions/model.TokenErrorResponse'
        "500":
          description: 服务器错误返回
          schema:
            $ref: '#/definitions/model.ServerErrorResponse'
      summary: 生成id_token
swagger: "2.0"
